CouchPlayerServer/Models/ErrorViewModel.cs
using System;

namespace CouchPlayerServer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CouchPlayerServer/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Contracts;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace CouchPlayerServer.Controllers
{
    public class TestController : Controller
    {
        public IActionResult Index2()
        {
            return View();
        }

        // Backup
        private IRepositoryWrapper mRepoWrapper;


        public TestController(IRepositoryWrapper repoWrapper)
        {
            mRepoWrapper = repoWrapper;
        }


        public IActionResult Index()
        {

            VideoElement tmpElem = new VideoElement();
            tmpElem.Id = 1;
            tmpElem.Title = "Test";

            tmpElem.IsFolderElement = false;
            tmpElem.FileFormat = "mp4";
            tmpElem.FileName = "test.mp4";
            tmpElem.Path = "C:\temp";
            tmpElem.FullPath = "C:\temp\test.mp4";
            tmpElem.Duration = new TimeSpan();
            tmpElem.Framerate = 60;
            tmpElem.ResWidth = 1920;
            tmpElem.ResHeight = 1080;


            mRepoWrapper.VideoElements.Create(tmpElem);
            mRepoWrapper.VideoElements.Save();

            var video = mRepoWrapper.VideoElements.FindAll();


            return View();
        }

    }
}

CouchPlayerServer/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Common;
using Contracts;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using static Common.MediaCrawler;

namespace CouchPlayerServer.Controllers
{
    public class VideoController : Controller
    {
        private IRepositoryWrapper mRepoWrapper;


        public VideoController(IRepositoryWrapper repoWrapper)
        {
            mRepoWrapper = repoWrapper;
        }


        [HttpGet]
        public IActionResult Index()
        {

            VideoElement tmpElem = new VideoElement();
            tmpElem.Id = 2;
            tmpElem.Title = "Test";

            tmpElem.IsFolderElement = false;
            tmpElem.FileFormat = "mp4";
            tmpElem.FileName = "test.mp4";
            tmpElem.Path = "C:\temp";
            tmpElem.FullPath = "C:\temp\test.mp4";
            tmpElem.Duration = new TimeSpan();
            tmpElem.Framerate = 60;
            tmpElem.ResWidth = 1920;
            tmpElem.ResHeight = 1080;


            //mRepoWrapper.VideoElements.Create(tmpElem);
            //mRepoWrapper.VideoElements.Save();

            var video = mRepoWrapper.VideoElements.FindAll();

            List<VideoElement> tmpVideos = mRepoWrapper.VideoElements.FindAll().ToList();

            return View(tmpVideos);
        }

        [HttpGet]
        public IActionResult GetAllVideos()
        {

            List<VideoElement> tmpVideos = mRepoWrapper.VideoElements.FindAll().ToList();


            return View();
        }


        [HttpGet]
        public IActionResult ShowVideo(int id)
        {

            List<VideoElement> tmpVideos = mRepoWrapper.VideoElements.FindAll().ToList();

            List<FileInfo> tmpLocalVideos = MediaCrawler.GetFilesByType(MediaTypes.Video, @"D:\HandtkeA\Vertraulich\tmp\Android_Backup\MobileBackup\Data\2018-09-04-132707\Video\Movies\Sonstige", true);

            foreach (var video in tmpLocalVideos)
            {

                bool tmpIsDuplicate = tmpVideos.Where(v => v.Title == video.Name).Any();

                if (!tmpIsDuplicate)
                {
                    VideoElement tmpElem = new VideoElement();

                    tmpElem.Title = video.Name;
                    tmpElem.IsFolderElement = false;
                    tmpElem.FileFormat = video.Extension.ToLower();
                    tmpElem.FileName = video.Name;
                    tmpElem.Path = video.FullName;
                    tmpElem.FullPath = "C:\temp\test.mp4";
                    tmpElem.Duration = new TimeSpan();
                    tmpElem.Framerate = 60;
                    tmpElem.ResWidth = 1920;
                    tmpElem.ResHeight = 1080;

                    mRepoWrapper.VideoElements.Create(tmpElem);
                    mRepoWrapper.VideoElements.Save();
                }

            }

            return View("Index", tmpVideos);
        }


    }
}

CouchPlayerServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CouchPlayerServer</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CouchPlayerServer</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CouchPlayerServer</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CouchPlayerServer/Views/Test/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CouchPlayerServer/Views/Video/Index.cshtml
@model IEnumerable<Entities.Models.VideoElement>

@{
    ViewData["Title"] = "Videos";
}

<h2>View</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsFolderElement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileFormat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullPath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Framerate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResWidth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThumbnailFile)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsFolderElement)
                </td>
                <td>
                    @Html.ActionLink("Testvideo", "ShowVideo", "Video", new { id = item.Id }, null)
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileFormat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Path)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullPath)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Framerate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ResWidth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ResHeight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThumbnailFile)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

CouchPlayerServer/Views/Video/View.cshtml
@model IEnumerable<Entities.Models.VideoElement>

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsFolderElement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileFormat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Path)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullPath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Framerate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResWidth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ResHeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThumbnailFile)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsFolderElement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileFormat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Path)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullPath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Framerate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ResWidth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ResHeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThumbnailFile)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>